const CATEGORY_ENDPOINT = '/category';
const CHANNEL_ENDPOINT = '/channel';
const MESSAGE_ENDPOINT = '/message';
const NOTIFICATION_ENDPOINT = '/notification';
const USER_ENDPOINT = '/user';


export {
  CATEGORY_ENDPOINT,
  CHANNEL_ENDPOINT,
  MESSAGE_ENDPOINT,
  NOTIFICATION_ENDPOINT,
  USER_ENDPOINT
};